# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170727_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tb20161130',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuhao', models.CharField(max_length=8)),
                ('editor', models.CharField(max_length=50)),
                ('banming', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=45)),
                ('imgsrc', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'tb_2016_11_30',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tb20170801',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuhao', models.CharField(max_length=8)),
                ('editor', models.CharField(max_length=50)),
                ('banming', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=45)),
                ('imgsrc', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['xuhao'],
                'db_table': 'tb_2017_08_07',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='tag',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
