# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170807_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb20170801',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
