# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170807_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb20170801',
            options={'managed': False, 'ordering': ['xuhao']},
        ),
    ]
