# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170807_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('xuhao', models.CharField(max_length=8)),
                ('editor', models.CharField(max_length=50)),
                ('banming', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=45)),
                ('imgsrc', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['xuhao'],
                'db_table': 'tb_2017_09_30',
                'managed': False,
            },
        ),
    ]
